package com.usa.controller;

import com.usa.model.domain.login.Permiso;
import com.usa.model.domain.login.Rol;
import com.usa.model.domain.login.RolPermiso;
import com.usa.model.domain.login.Usuario;
import com.usa.model.domain.marca.Marca;
import com.usa.model.domain.modelo.Modelo;
import com.usa.model.domain.tipo.Tipo;
import com.usa.repository.*;
import com.usa.util.Endpoint;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@RestController
@RequestMapping(Endpoint.home)
@CrossOrigin
public class HomeController
{
    @Autowired
    MarcaRepository marcaRepository;
    @Autowired
    ModeloRepository modeloRepository;
    @Autowired
    TipoRepository tipoRepository;
    @Autowired
    UsuarioRepository usuarioRepository;
    @Autowired
    RolRepository rolRepository;
    @Autowired
    RolPermisoRepository rolPermisoRepository;
    @Autowired
    PermisoRepository permisoRepository;
    
    @GetMapping
    public String loadData() {
        final Permiso permiso = new Permiso();
        permiso.setDescripcion("ALL");
        permisoRepository.save(permiso);
        final Rol rol = new Rol();
        rol.setDescripcion("admin");
        rol.setNombreRol("admin");
        rolRepository.save(rol);
        final RolPermiso rolPermiso = new RolPermiso();
        rolPermiso.setPermiso(permiso);
        rolPermiso.setRol(rol);
        rolPermisoRepository.save(rolPermiso);
        final Usuario usuario = new Usuario();
        usuario.setUsuario("admin");
        usuario.setPassword("Hum@n5242@");
        usuario.setRol(rol);
        usuarioRepository.save(usuario);
        final List<Tipo> tipos = new ArrayList<Tipo>();
        tipos.add(new Tipo("Carro", new Date(), true));
        tipos.add(new Tipo("Camión", new Date(), true));
        tipos.add(new Tipo("Motor", new Date(), true));
        tipoRepository.saveAll(tipos);
        final List<Marca> marcas = new ArrayList<Marca>();
        marcas.add(new Marca("Acura", new Date(), true));
        marcas.add(new Marca("Alfa Romeo", new Date(), true));
        marcas.add(new Marca("Aston Martin", new Date(), true));
        marcas.add(new Marca("Audi", new Date(), true));
        marcas.add(new Marca("Autiny", new Date(), true));
        marcas.add(new Marca("Bajaj", new Date(), true));
        marcas.add(new Marca("Bentley", new Date(), true));
        marcas.add(new Marca("BMW", new Date(), true));
        marcas.add(new Marca("Brilliance", new Date(), true));
        marcas.add(new Marca("Buick", new Date(), true));
        marcas.add(new Marca("BYD", new Date(), true));
        marcas.add(new Marca("Cadillac", new Date(), true));
        marcas.add(new Marca("Chana", new Date(), true));
        marcas.add(new Marca("Changan", new Date(), true));
        marcas.add(new Marca("Chery", new Date(), true));
        marcas.add(new Marca("Chevrolet", new Date(), true));
        marcas.add(new Marca("Chrysler", new Date(), true));
        marcas.add(new Marca("Citroen", new Date(), true));
        marcas.add(new Marca("Daewoo", new Date(), true));
        marcas.add(new Marca("Daihatsu", new Date(), true));
        marcas.add(new Marca("DFM", new Date(), true));
        marcas.add(new Marca("Dodge", new Date(), true));
        marcas.add(new Marca("Dongfeng", new Date(), true));
        marcas.add(new Marca("Ferrari", new Date(), true));
        marcas.add(new Marca("Fiat", new Date(), true));
        marcas.add(new Marca("Ford", new Date(), true));
        marcas.add(new Marca("Geo", new Date(), true));
        marcas.add(new Marca("GMC", new Date(), true));
        marcas.add(new Marca("Higer", new Date(), true));
        marcas.add(new Marca("Honda", new Date(), true));
        marcas.add(new Marca("Hummer", new Date(), true));
        marcas.add(new Marca("Hyundai", new Date(), true));
        marcas.add(new Marca("Infiniti", new Date(), true));
        marcas.add(new Marca("Isuzu", new Date(), true));
        marcas.add(new Marca("Jac", new Date(), true));
        marcas.add(new Marca("Jaguar", new Date(), true));
        marcas.add(new Marca("Jeep", new Date(), true));
        marcas.add(new Marca("Jin-Bei", new Date(), true));
        marcas.add(new Marca("JMC", new Date(), true));
        marcas.add(new Marca("Kaiyun", new Date(), true));
        marcas.add(new Marca("Kia", new Date(), true));
        marcas.add(new Marca("Lamborghini", new Date(), true));
        marcas.add(new Marca("Land Rover", new Date(), true));
        marcas.add(new Marca("Landwind", new Date(), true));
        marcas.add(new Marca("Lexus", new Date(), true));
        marcas.add(new Marca("Lincoln", new Date(), true));
        marcas.add(new Marca("Linfan", new Date(), true));
        marcas.add(new Marca("Lotus", new Date(), true));
        marcas.add(new Marca("Mahindra", new Date(), true));
        marcas.add(new Marca("Maserati", new Date(), true));
        marcas.add(new Marca("Maxus", new Date(), true));
        marcas.add(new Marca("Mazda", new Date(), true));
        marcas.add(new Marca("McLaren", new Date(), true));
        marcas.add(new Marca("Mercedes-Benz", new Date(), true));
        marcas.add(new Marca("Mercury", new Date(), true));
        marcas.add(new Marca("MG", new Date(), true));
        marcas.add(new Marca("Mini", new Date(), true));
        marcas.add(new Marca("Mitsubishi", new Date(), true));
        marcas.add(new Marca("Nissan", new Date(), true));
        marcas.add(new Marca("Peugeot", new Date(), true));
        marcas.add(new Marca("Plymouth", new Date(), true));
        marcas.add(new Marca("Pontiac", new Date(), true));
        marcas.add(new Marca("Porsche", new Date(), true));
        marcas.add(new Marca("Ram", new Date(), true));
        marcas.add(new Marca("Renault", new Date(), true));
        marcas.add(new Marca("Rolls Royce", new Date(), true));
        marcas.add(new Marca("Samsung", new Date(), true));
        marcas.add(new Marca("Seat", new Date(), true));
        marcas.add(new Marca("Sem", new Date(), true));
        marcas.add(new Marca("Shineray", new Date(), true));
        marcas.add(new Marca("Skoda", new Date(), true));
        marcas.add(new Marca("Smart", new Date(), true));
        marcas.add(new Marca("SsangYong", new Date(), true));
        marcas.add(new Marca("Subaru", new Date(), true));
        marcas.add(new Marca("Suzuki", new Date(), true));
        marcas.add(new Marca("Tesla", new Date(), true));
        marcas.add(new Marca("Toyota", new Date(), true));
        marcas.add(new Marca("Victory", new Date(), true));
        marcas.add(new Marca("Volkswagen", new Date(), true));
        marcas.add(new Marca("Volvo", new Date(), true));
        marcaRepository.saveAll((Iterable)marcas);
        final List<Modelo> models = new ArrayList<Modelo>();
        models.add(new Modelo("Todos los Modelos", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("ILX", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("MDX", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("NSX", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("RDX", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("RL", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("T L", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("TLX", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("TSX", new Date(), true, (Marca)marcaRepository.findById(1L).get()));
        models.add(new Modelo("Stelvio", new Date(), true, (Marca)marcaRepository.findById(2L).get()));
        models.add(new Modelo("DB9", new Date(), true, (Marca)marcaRepository.findById(3L).get()));
        models.add(new Modelo("A3", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("A4", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("A5", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("A6", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("A7", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("A8", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("Q3", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("Q5", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("Q7", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("Q8", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("R8", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("RS3", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("S3", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("S4", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("S5", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("S6", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("S7", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("SQ5", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("TT", new Date(), true, (Marca)marcaRepository.findById(4L).get()));
        models.add(new Modelo("M1", new Date(), true, (Marca)marcaRepository.findById(5L).get()));
        models.add(new Modelo("Qute", new Date(), true, (Marca)marcaRepository.findById(6L).get()));
        models.add(new Modelo("Bentayga", new Date(), true, (Marca)marcaRepository.findById(7L).get()));
        models.add(new Modelo("MK VI", new Date(), true, (Marca)marcaRepository.findById(7L).get()));
        models.add(new Modelo("i3", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("i8", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie 1", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie 3", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie 4", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie 5", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie 6", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie 7", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie M", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("Serie X", new Date(), true, (Marca)marcaRepository.findById(8L).get()));
        models.add(new Modelo("V3", new Date(), true, (Marca)marcaRepository.findById(9L).get()));
        models.add(new Modelo("V6", new Date(), true, (Marca)marcaRepository.findById(9L).get()));
        models.add(new Modelo("Special", new Date(), true, (Marca)marcaRepository.findById(10L).get()));
        models.add(new Modelo("F0", new Date(), true, (Marca)marcaRepository.findById(11L).get()));
        models.add(new Modelo("F3", new Date(), true, (Marca)marcaRepository.findById(11L).get()));
        models.add(new Modelo("S6", new Date(), true, (Marca)marcaRepository.findById(11L).get()));
        models.add(new Modelo("Tang", new Date(), true, (Marca)marcaRepository.findById(11L).get()));
        models.add(new Modelo("Yuan ev", new Date(), true, (Marca)marcaRepository.findById(11L).get()));
        models.add(new Modelo("ATS", new Date(), true, (Marca)marcaRepository.findById(12L).get()));
        models.add(new Modelo("De Ville", new Date(), true, (Marca)marcaRepository.findById(12L).get()));
        models.add(new Modelo("Escalade", new Date(), true, (Marca)marcaRepository.findById(12L).get()));
        models.add(new Modelo("XTS", new Date(), true, (Marca)marcaRepository.findById(12L).get()));
        models.add(new Modelo("Benni EV180", new Date(), true, (Marca)marcaRepository.findById(13L).get()));
        models.add(new Modelo("Minitruck", new Date(), true, (Marca)marcaRepository.findById(13L).get()));
        models.add(new Modelo("Star 5", new Date(), true, (Marca)marcaRepository.findById(13L).get()));
        models.add(new Modelo("CS", new Date(), true, (Marca)marcaRepository.findById(14L).get()));
        models.add(new Modelo("CS 55", new Date(), true, (Marca)marcaRepository.findById(14L).get()));
        models.add(new Modelo("tiggo", new Date(), true, (Marca)marcaRepository.findById(15L).get()));
        models.add(new Modelo("Astro", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Avalanche", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Aveo", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Bolt", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Camaro", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Captiva", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("chevy C2", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("CMP", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Cobalt", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Colorado", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Corvette", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Cruze", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Epica", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Equinox", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Express", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("HHR", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Impala", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Lumina", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Malibu", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("N 300", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("N 400", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Nova", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Optra", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Orlando", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Pick Up", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("S 10", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Silverado", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Sonic", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Spark", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("SSR", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Suburban", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Tahoe", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Tracker", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Trail blazer", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Traverse", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Trax", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("Uplander", new Date(), true, (Marca)marcaRepository.findById(16L).get()));
        models.add(new Modelo("200", new Date(), true, (Marca)marcaRepository.findById(17L).get()));
        models.add(new Modelo("300", new Date(), true, (Marca)marcaRepository.findById(17L).get()));
        models.add(new Modelo("New York", new Date(), true, (Marca)marcaRepository.findById(17L).get()));
        models.add(new Modelo("Sebring", new Date(), true, (Marca)marcaRepository.findById(17L).get()));
        models.add(new Modelo("Town  Country", new Date(), true, (Marca)marcaRepository.findById(17L).get()));
        models.add(new Modelo("Berlingo", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("C-Elys\u00e9e", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("C3", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("C5", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("DS3", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("DS4", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("jumper", new Date(), true, (Marca)marcaRepository.findById(18L).get()));
        models.add(new Modelo("Damas", new Date(), true, (Marca)marcaRepository.findById(19L).get()));
        models.add(new Modelo("Labo", new Date(), true, (Marca)marcaRepository.findById(19L).get()));
        models.add(new Modelo("Lanos", new Date(), true, (Marca)marcaRepository.findById(19L).get()));
        models.add(new Modelo("Atrai", new Date(), true, (Marca)marcaRepository.findById(20L).get()));
        models.add(new Modelo("Boon", new Date(), true, (Marca)marcaRepository.findById(20L).get()));
        models.add(new Modelo("Hijet", new Date(), true, (Marca)marcaRepository.findById(20L).get()));
        models.add(new Modelo("Mira", new Date(), true, (Marca)marcaRepository.findById(20L).get()));
        models.add(new Modelo("Sirion", new Date(), true, (Marca)marcaRepository.findById(20L).get()));
        models.add(new Modelo("Terios", new Date(), true, (Marca)marcaRepository.findById(20L).get()));
        models.add(new Modelo("Cargo Van", new Date(), true, (Marca)marcaRepository.findById(21L).get()));
        models.add(new Modelo("Donfeng", new Date(), true, (Marca)marcaRepository.findById(21L).get()));
        models.add(new Modelo("Avenger", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Caliber", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Caravan", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Challenger", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Charger", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Dart", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Durango", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Grand Caravan", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Journey", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("Ram", new Date(), true, (Marca)marcaRepository.findById(22L).get()));
        models.add(new Modelo("AX4", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("AX7", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Cargo Box", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Dfsk", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Glory 560", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Mini Truck", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Minivan", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Rich 6", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("Star Bus", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("ZNA", new Date(), true, (Marca)marcaRepository.findById(23L).get()));
        models.add(new Modelo("458", new Date(), true, (Marca)marcaRepository.findById(24L).get()));
        models.add(new Modelo("488", new Date(), true, (Marca)marcaRepository.findById(24L).get()));
        models.add(new Modelo("488 Spyder", new Date(), true, (Marca)marcaRepository.findById(24L).get()));
        models.add(new Modelo("California", new Date(), true, (Marca)marcaRepository.findById(24L).get()));
        models.add(new Modelo("F-430", new Date(), true, (Marca)marcaRepository.findById(24L).get()));
        models.add(new Modelo("500", new Date(), true, (Marca)marcaRepository.findById(25L).get()));
        models.add(new Modelo("Fullback", new Date(), true, (Marca)marcaRepository.findById(25L).get()));
        models.add(new Modelo("Punto", new Date(), true, (Marca)marcaRepository.findById(25L).get()));
        models.add(new Modelo("C Max", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("E-150", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("E-250", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("E-350", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Eco Sport", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Econoline", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("EDGE", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Escape", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Expedition", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Explorer", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("F 150", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("F 250", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("F 350", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("F-450", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Farcon", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Fiesta", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Figo", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Focus", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Freestyle", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Fusion", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Mustang", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Ranger", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("T-350", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Taurus", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Thunderbird", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Transit", new Date(), true, (Marca)marcaRepository.findById(26L).get()));
        models.add(new Modelo("Tracker", new Date(), true, (Marca)marcaRepository.findById(27L).get()));
        models.add(new Modelo("Acadia", new Date(), true, (Marca)marcaRepository.findById(28L).get()));
        models.add(new Modelo("Denali", new Date(), true, (Marca)marcaRepository.findById(28L).get()));
        models.add(new Modelo("Sierra", new Date(), true, (Marca)marcaRepository.findById(28L).get()));
        models.add(new Modelo("Terrain", new Date(), true, (Marca)marcaRepository.findById(28L).get()));
        models.add(new Modelo("Yukon", new Date(), true, (Marca)marcaRepository.findById(28L).get()));
        models.add(new Modelo("16 Pasajeros", new Date(), true, (Marca)marcaRepository.findById(29L).get()));
        models.add(new Modelo("19 Pasajeros", new Date(), true, (Marca)marcaRepository.findById(29L).get()));
        models.add(new Modelo("Accord", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Acty", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("City", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Civic", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("CR-V", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("CR-Z", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Crosstour", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Element", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Fit", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("HR-V", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Insight", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Life", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Odyssey", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Pilot", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("Ridgeline", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("S 2000", new Date(), true, (Marca)marcaRepository.findById(30L).get()));
        models.add(new Modelo("H 1", new Date(), true, (Marca)marcaRepository.findById(31L).get()));
        models.add(new Modelo("H 2", new Date(), true, (Marca)marcaRepository.findById(31L).get()));
        models.add(new Modelo("H3", new Date(), true, (Marca)marcaRepository.findById(31L).get()));
        models.add(new Modelo("Accent", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Avante", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Cantus", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("County", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Elantra", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Genesis", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Grand I 10", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Grand Santa Fe", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Grandeur", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("H 1", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("H350", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("i 10", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("i 20", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Ioniq", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Palisade", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Santa Fe", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Sonata", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Starex", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Tucson", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Veloster", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Venue", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Veracruz", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("Verna", new Date(), true, (Marca)marcaRepository.findById(32L).get()));
        models.add(new Modelo("EX-35", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("F35", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("FX-35", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("FX-37", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("G-35", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("G-37", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("JX-35", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("Q-50", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("Q-60S", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("QX-30", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("QX-50", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("QX-56", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("QX-60", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("QX-70", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("QX-80", new Date(), true, (Marca)marcaRepository.findById(33L).get()));
        models.add(new Modelo("Ascender", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("Bighorn", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("Camioneta", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("DMAX", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("Kb", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("Mux", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("Rodeo", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("Trooper", new Date(), true, (Marca)marcaRepository.findById(34L).get()));
        models.add(new Modelo("EV1", new Date(), true, (Marca)marcaRepository.findById(35L).get()));
        models.add(new Modelo("S2", new Date(), true, (Marca)marcaRepository.findById(35L).get()));
        models.add(new Modelo("S3", new Date(), true, (Marca)marcaRepository.findById(35L).get()));
        models.add(new Modelo("X J", new Date(), true, (Marca)marcaRepository.findById(36L).get()));
        models.add(new Modelo("XK", new Date(), true, (Marca)marcaRepository.findById(36L).get()));
        models.add(new Modelo("XK8", new Date(), true, (Marca)marcaRepository.findById(36L).get()));
        models.add(new Modelo("Cherokee", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Comander", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Compass", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Gladiator", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Grand Cherokee", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Liberty", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Patriot", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Renegade", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Wrangler", new Date(), true, (Marca)marcaRepository.findById(37L).get()));
        models.add(new Modelo("Haise", new Date(), true, (Marca)marcaRepository.findById(38L).get()));
        models.add(new Modelo("JX 6571", new Date(), true, (Marca)marcaRepository.findById(39L).get()));
        models.add(new Modelo("Vigus", new Date(), true, (Marca)marcaRepository.findById(39L).get()));
        models.add(new Modelo("Pickman", new Date(), true, (Marca)marcaRepository.findById(40L).get()));
        models.add(new Modelo("Bongo", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Carnival", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Cerato", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Forte", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("K-3", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("K-5", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("K-7", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Lotze", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Morning", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Optima", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Picanto", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Rio", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Sedena", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Sedona", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Seltos", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Soluto", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Sorento", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Soul", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Sportage", new Date(), true, (Marca)marcaRepository.findById(41L).get()));
        models.add(new Modelo("Urus", new Date(), true, (Marca)marcaRepository.findById(42L).get()));
        models.add(new Modelo("Defender", new Date(), true, (Marca)marcaRepository.findById(43L).get()));
        models.add(new Modelo("Discovery", new Date(), true, (Marca)marcaRepository.findById(43L).get()));
        models.add(new Modelo("Freelander", new Date(), true, (Marca)marcaRepository.findById(43L).get()));
        models.add(new Modelo("Range Rover", new Date(), true, (Marca)marcaRepository.findById(43L).get()));
        models.add(new Modelo("x2", new Date(), true, (Marca)marcaRepository.findById(44L).get()));
        models.add(new Modelo("CT", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("ES", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("GS", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("GX", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("IS", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("LS", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("LX", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("NX", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("RX", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("UX", new Date(), true, (Marca)marcaRepository.findById(45L).get()));
        models.add(new Modelo("Aviator", new Date(), true, (Marca)marcaRepository.findById(46L).get()));
        models.add(new Modelo("MKC", new Date(), true, (Marca)marcaRepository.findById(46L).get()));
        models.add(new Modelo("MKS", new Date(), true, (Marca)marcaRepository.findById(46L).get()));
        models.add(new Modelo("MKZ", new Date(), true, (Marca)marcaRepository.findById(46L).get()));
        models.add(new Modelo("Navigator", new Date(), true, (Marca)marcaRepository.findById(46L).get()));
        models.add(new Modelo("Town Car", new Date(), true, (Marca)marcaRepository.findById(46L).get()));
        models.add(new Modelo("Minibus", new Date(), true, (Marca)marcaRepository.findById(47L).get()));
        models.add(new Modelo("Elise", new Date(), true, (Marca)marcaRepository.findById(48L).get()));
        models.add(new Modelo("Bolero", new Date(), true, (Marca)marcaRepository.findById(49L).get()));
        models.add(new Modelo("Ghibli", new Date(), true, (Marca)marcaRepository.findById(50L).get()));
        models.add(new Modelo("Gran Turismo", new Date(), true, (Marca)marcaRepository.findById(50L).get()));
        models.add(new Modelo("Levante", new Date(), true, (Marca)marcaRepository.findById(50L).get()));
        models.add(new Modelo("Quattroporte", new Date(), true, (Marca)marcaRepository.findById(50L).get()));
        models.add(new Modelo("T60", new Date(), true, (Marca)marcaRepository.findById(51L).get()));
        models.add(new Modelo("V80 Cargo Van", new Date(), true, (Marca)marcaRepository.findById(51L).get()));
        models.add(new Modelo("2", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("3", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("5", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("6", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("626", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Bongo", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("BT-50", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Carol", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("CX-3", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("CX-30", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("CX-5", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("CX-7", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("CX-9", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Demio", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Euno Roadster", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Familia Van", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("MPV", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Premacy", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Protege", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("RX-8", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("Tribute", new Date(), true, (Marca)marcaRepository.findById(52L).get()));
        models.add(new Modelo("570", new Date(), true, (Marca)marcaRepository.findById(53L).get()));
        models.add(new Modelo("600", new Date(), true, (Marca)marcaRepository.findById(53L).get()));
        models.add(new Modelo("720", new Date(), true, (Marca)marcaRepository.findById(53L).get()));
        models.add(new Modelo("Clase A", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase C", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase CL", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase CLA", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase CLS", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase D", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase E", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase G", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GL", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GLA", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GLC", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GLE", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GLK", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GLS", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase GT", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase ML", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase R", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase S", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase SL", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase SLC", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase SLK", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase V", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Clase X", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("SEC", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Smart", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Sprinter", new Date(), true, (Marca)marcaRepository.findById(54L).get()));
        models.add(new Modelo("Gran Marquis", new Date(), true, (Marca)marcaRepository.findById(55L).get()));
        models.add(new Modelo("350", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("360", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("550", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("GS", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("MG3", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("Morris Z S", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("ZS", new Date(), true, (Marca)marcaRepository.findById(56L).get()));
        models.add(new Modelo("Cooper", new Date(), true, (Marca)marcaRepository.findById(57L).get()));
        models.add(new Modelo("ASX", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Chariot", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Eclipse", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Endeavor", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Evolution", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Galant", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("L 200", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("L 300", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Lancer", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Minicab Truck", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Mirage", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Montero", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Montero Sport", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Nativa", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Outlander", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("Pajero", new Date(), true, (Marca)marcaRepository.findById(58L).get()));
        models.add(new Modelo("1200", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("300 ZX", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("350 Z", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("370-Z", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Ad Van", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Ad Wagon", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Almera", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Altima", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Caravan", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Cube", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("D 21", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("D 22", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Frontier", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("GT-R", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Juke", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Kicks", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Latio", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Leaf", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("March", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Maxima", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Murano", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Navara", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Note", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("NV", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Pathfinder", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Patrol", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Qashqai", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Quest", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Rogue", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Sentra", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Serena", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Silvia", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Skyline", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("TIIDA", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("TITAN", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Urvan", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Vanette", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Versa", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("X-Trail", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("Xterra", new Date(), true, (Marca)marcaRepository.findById(59L).get()));
        models.add(new Modelo("2008", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("206", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("207", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("208", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("3008", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("301", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("406", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("407", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("5008", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("508", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("607", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("Boxer", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("Partner", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("Rifter", new Date(), true, (Marca)marcaRepository.findById(60L).get()));
        models.add(new Modelo("Grand Voyager", new Date(), true, (Marca)marcaRepository.findById(61L).get()));
        models.add(new Modelo("Safari", new Date(), true, (Marca)marcaRepository.findById(62L).get()));
        models.add(new Modelo("Vibes", new Date(), true, (Marca)marcaRepository.findById(62L).get()));
        models.add(new Modelo("911", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Boxster", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Carrera", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Cayenne", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Cayman", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("GT4", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Macan", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Panamera", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Targa", new Date(), true, (Marca)marcaRepository.findById(63L).get()));
        models.add(new Modelo("Promaster", new Date(), true, (Marca)marcaRepository.findById(64L).get()));
        models.add(new Modelo("Captur", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Dokker", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Duster", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Fluence", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Kangoo", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Koleos", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Logan", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Megane", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Sandero", new Date(), true, (Marca)marcaRepository.findById(65L).get()));
        models.add(new Modelo("Phamtom", new Date(), true, (Marca)marcaRepository.findById(66L).get()));
        models.add(new Modelo("Silver Spur", new Date(), true, (Marca)marcaRepository.findById(66L).get()));
        models.add(new Modelo("SM5", new Date(), true, (Marca)marcaRepository.findById(67L).get()));
        models.add(new Modelo("Ateca", new Date(), true, (Marca)marcaRepository.findById(68L).get()));
        models.add(new Modelo("Cargo Standard", new Date(), true, (Marca)marcaRepository.findById(69L).get()));
        models.add(new Modelo("A-9 Cargo", new Date(), true, (Marca)marcaRepository.findById(70L).get()));
        models.add(new Modelo("T-20", new Date(), true, (Marca)marcaRepository.findById(70L).get()));
        models.add(new Modelo("T-20 Cargo Box", new Date(), true, (Marca)marcaRepository.findById(70L).get()));
        models.add(new Modelo("X 30L", new Date(), true, (Marca)marcaRepository.findById(70L).get()));
        models.add(new Modelo("X30", new Date(), true, (Marca)marcaRepository.findById(70L).get()));
        models.add(new Modelo("Fabia", new Date(), true, (Marca)marcaRepository.findById(71L).get()));
        models.add(new Modelo("Kodiaq", new Date(), true, (Marca)marcaRepository.findById(71L).get()));
        models.add(new Modelo("Octavia", new Date(), true, (Marca)marcaRepository.findById(71L).get()));
        models.add(new Modelo("Brabus Forfour", new Date(), true, (Marca)marcaRepository.findById(72L).get()));
        models.add(new Modelo("Passion Fortwo", new Date(), true, (Marca)marcaRepository.findById(72L).get()));
        models.add(new Modelo("Actyon", new Date(), true, (Marca)marcaRepository.findById(73L).get()));
        models.add(new Modelo("Korando", new Date(), true, (Marca)marcaRepository.findById(73L).get()));
        models.add(new Modelo("Musso", new Date(), true, (Marca)marcaRepository.findById(73L).get()));
        models.add(new Modelo("Rexton", new Date(), true, (Marca)marcaRepository.findById(73L).get()));
        models.add(new Modelo("Tivoli", new Date(), true, (Marca)marcaRepository.findById(73L).get()));
        models.add(new Modelo("BRZ", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Crosstrek", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Forester", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Impreza", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Legacy", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Outback", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Pleo", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Sambar", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Tribeca", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("XV", new Date(), true, (Marca)marcaRepository.findById(74L).get()));
        models.add(new Modelo("Alto", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("APV", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Celerio", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Ciaz", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Equator", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Every", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Forenza", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Grand Vitara", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Jimny", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Kizashi", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Reno", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("S-Cross", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Saiki", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Swift", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("SX 4", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Vitara", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("XL7", new Date(), true, (Marca)marcaRepository.findById(75L).get()));
        models.add(new Modelo("Model", new Date(), true, (Marca)marcaRepository.findById(76L).get()));
        models.add(new Modelo("4 Runner", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Agya", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Aqua", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Avalon", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("C-HR", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Camry", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Celica", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Corolla", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Corona", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Duet", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Fielder", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("FJ Cruiser", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Fortuner", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Hiace", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Highlander", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Hilux", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Hilux Surf", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Land Cruiser", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Land Cruiser Prado", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Lite-Ace", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Matrix", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Passo", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Pick Up", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Pixis", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Prius", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Probox", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("RAV4", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Rush", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Scion", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Sequoia", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Sienna", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Starlet", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Supra", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Tacoma", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Tiara", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Town-Ace", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Tundra", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Venza", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("VITZ", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Yaris", new Date(), true, (Marca)marcaRepository.findById(77L).get()));
        models.add(new Modelo("Jupiter", new Date(), true, (Marca)marcaRepository.findById(78L).get()));
        models.add(new Modelo("Amarok", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Beetle", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Bora", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("CC", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Crossfox", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Golf", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("GTI", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Jetta", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Passat", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Rabbit", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("T-Cross", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Tiguan", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Touareg", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("Transporter", new Date(), true, (Marca)marcaRepository.findById(79L).get()));
        models.add(new Modelo("XC40", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("S40", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("S60", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("S90", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("V60", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("V90", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("XC60", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        models.add(new Modelo("XC90", new Date(), true, (Marca)marcaRepository.findById(80L).get()));
        modeloRepository.saveAll(models);
        return "Ok";
    }
}
